version: '1.0.{build}'

branches:
  only:
  - master
  - Development

configuration:
- Debug
- Release

platform: Any CPU

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  SNK_PASSPHRASE:
    secure: hAvbiLFI38bO0EdEXv77Xk0P3slfTlGq+jaD5JY0VaE=
  SNK_SALT:
    secure: F/vXSd1ELO8L1EkLnaFLgoWgayckxYQmtnWqa/CI05M=
  SNK_INIT:
    secure: i+0xK/acnRfh2XY8FjUR9LPlbP+HyPadahLxlrQnB58=


init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- appveyor-retry dotnet restore -v Minimal
- ps: C:\projects\jmespath-net\bin\EncryptDecryptFile.PS1

build_script:
- dotnet build "src\jmespath.net" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- ps: C:\projects\jmespath-net\src\jmespath.net.signed\update-version.ps1
- dotnet build "src\jmespath.net.signed" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%

after_build:
- dotnet pack "src\jmespath.net.signed" -c Release

test_script:
- dotnet test "tests\jmespathnet.tests" -c %CONFIGURATION%

artifacts:
  - path: '**\*.nupkg'
    name: NuGet package

deploy:
- provider: NuGet
  api_key:
    secure: 7gxD0EFIAMoBuDwpPoqN0dwOcCY4udY7SmoCgyoLaYl+2Akn0UXmQ8sOP1kOcGhD
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master

cache:
- '%USERPROFILE%\.nuget\packages'

on_finish:
